include theos/makefiles/common.mk

BUNDLE_NAME = AppstoreNoHistorySettings
AppstoreNoHistorySettings_FILES = /mnt/d/codes/appstorenohistory/appstorenohistorysettings/AppstoreNoHistorySettingsController.mm
AppstoreNoHistorySettings_INSTALL_PATH = /Library/PreferenceBundles
AppstoreNoHistorySettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
AppstoreNoHistorySettings_PRIVATE_FRAMEWORKS = Preferences
AppstoreNoHistorySettings_CFLAGS = -fobjc-arc
AppstoreNoHistorySettings_LDFLAGS = -Wl,-segalign,4000
AppstoreNoHistorySettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk
